version: '3.8'
services:
  whodrinksapi:
    build:
      context: ./WhoDrinks.Api
      dockerfile: Dockerfile
    expose:
      - "5000"
    restart: always
  reverseproxy:
    build:
      context: ./reverseproxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    links :
      - whodrinksapi